name: Integración Continua

on:
  push:
  pull_request:


jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: 'Grant execute permissions for gradlew'
        run: chmod +x gradlew
      
      - name: Build with Gradle
        run: ./gradlew build